### ISSUE TITLE
Make Und-Vam playable

### ISSUE THREAD

**Issue by hatcatter** [elunna/hackem#372]
Should Und-Vam be a valid combination (reason being blade)?
Should Dhampirs be added as a playable instead (https://en.wikipedia.org/wiki/Dhampir)?
If Und-Vam/Dha would be a valid combination should you have to prove that you are loyal to the Und war against undead by forcing you to kill Vlad or something along those lines before quest?

**Comment by elunna** [comment]
One issue, all the undead slayers starting weapons are silver or mostly silver.

**Comment by elunna** [comment]
Possible starting inventory:
- Long sword
- 3 silver stakes, shotgun or chakram
- Black trench coat, or just a leather jacket
- Black gloves, be generous and any random black gloves? Or just some gauntlets?
- High Boots
- Lenses? We don't have sunglasses so these are a close second.


Other thoughts:

- What do you do about food? Blade doesn't seem to drink blood, but does he eat??  Or do we just leave the regular drain attack and blood drinking abilities...
- Other vampire get familiars, so Blade should get no pets. The starting familiar might actually be something fun to add to the vampiric role in general instead of the standard dog/pet.
- Need is_blade macro to make implementing a lot of this stuff easier.
- What is Blade's alignment?  Undead slayers already have neutral as an option so allowing neutral vampires probably is the easiest way to slide them in.

**Comment by elunna** [comment]
Here is a new trench coat, adapted from the robe tile!

# tile 144 (robe)
{
  ................
  ......AAA.......
  .....ARRRAR.....
  ....AARNNAAR....
  .....ARNNARR....
  .....AANAARR....
  ....AAAAAAAR....
  ....AW0R0WRRR...
  ...AAAW0WAAAR...
  ...AAAA0AAAAR...
  ...AAAAWAARAR...
  ...AAAAAAARAR...
  ...AAAAWAARAR...
  ...AAAAAAARAR...
  ...RAAAAAARRR...
  ....RRRRRRRR....
}
