### ISSUE TITLE
No info on rogues gloves in /?

### ISSUE THREAD

**Issue by hatcatter** [elunna/hackem#376]
The lookup only mentions:

Armor, worn in the gloves slot.
Base AC 1.
Takes 1 turn to put on or remove.
Base cost 50, weighs 10 aum.
Is inherently magical.
Material: leather

**Comment by elunna** [comment]
Once you identify them, the lookup changes:
```
Object lookup for "pair of rogues gloves":

Armor, worn in the gloves slot.
Base AC 1, magic cancellation 0.
Takes 1 turn to put on or remove.
Base cost 50, weighs 10 aum.
Confers searching.
Is inherently magical.
Material: leather
```

Currently it's required to have the item identified for the lookup to show all the stats, otherwise a player could see what an unidentified item confers by just searching "fine gloves". This is not great for looking up the actual name because then we don't get the full info. It looks like an additional variable is probably needed, like "identified_doesnt_matter", so we can have the lookup work properly.
