### ISSUE TITLE
Tileset bug

### ISSUE THREAD

**Issue by YesLaching** [elunna/hackem#413]
Version 1.2.0-0 Beta downloaded for Windows

I don't play with tileset, but people who do, can't really play. The tiles are incorrect
![Screenshot 2023-07-30 210621](https://github.com/elunna/hackem/assets/140734691/d6e4b33a-626b-44ef-ba69-205d137f560e)

**Comment by elunna** [comment]
Thank you for the report - I was able to reproduce this as well.

**Comment by elunna** [comment]
I went back to the release build of 1.1.4-1 from July 18, and it was fine then, so that limits the scope a bit.

Notes:

- The character and monster tiles seem ok
- It's wall/room tiles that are incorrect (and mapped as monster tiles).
- Very suspect: b0d7425fe - Added spooky sounds to nightmare level (Tina Hall). (2 weeks ago) <Erik Lunna>

**Comment by elunna** [comment]
<img width="379" alt="image" src="https://github.com/elunna/hackem/assets/5000096/e64cc6fa-4472-4eb4-a4f3-5ae6294a0556">

**Comment by elunna** [comment]
This is fixed in the latest pre-release 1.2.1
