### ISSUE TITLE
Fire Bolt is a Flame Mage exclusive spell, shouldn't Ice Mage have also some exclusive spell e.g. Ice Bolt?

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#484]

**Comment by elunna** [comment]
Ahh, right. I originally added the exclusive thing because it was the first spell I had ever added and I think I got a bit carried away. It's probably fine for it to be accessible to the whole cast. Now that I understand force bolt and fire bolt more deeply, it has a fixed to-hit so it has some built in obsolescence for the late game. I think we can just open it up for the general public :)

The ice mage has a special ice armor tech as a counter to this spell.
